build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=psr2 ./src
  environment:
    php:
      version: 7.4
#    tests:
#      override:
#        - command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
#          coverage:
#            file: 'coverage.clover'
#            format: 'clover'
filter:
  excluded_paths:
    - 'bin/*'
    - 'tests/*'
    - 'public/assets/*'
    - 'public/assets-admin/*'
    - 'public/vendor/*'
    - '*.min.js'
checks:
  php: true
  javascript: true
