build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run --standard=psr2 ./src
    environment:
        php:
            # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm
            version: 7.4
#    tests:
#        override:
#            -
#                command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
#                coverage:
#                    file: 'coverage.clover'
#                    format: 'clover'
filter:
    excluded_paths:
        - 'bin/*'
        - 'tests/*'
        - 'public/assets/*'
        - 'public/assets-admin/*'
        - 'public/vendor/*'
        - '*.min.js'
checks:
    php: true
    javascript: true
