#index:
#    path: /
#    controller: App\Controller\DefaultController::index

panel_default:
  path: /p
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: panel
    permanent: true
    page: home
