easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

panel_default:
    path: /p
    controller: FrameworkBundle:Redirect:redirect
    defaults:
        route: panel
        permanent: true
        page: home
